language: python
dist: trusty
env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7
services:
  - postgres
before_install:
    - wget -q http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - conda create -n ramp --yes pip python=$PYTHON_VERSION ipykernel
    - source activate ramp
    - conda install --yes numpy pyyaml sqlalchemy psycopg2
    - conda install --yes pandas scikit-learn flask six unidecode termcolor
    - conda install --yes pytest pytest-cov jupyter gitpython
    - conda install --yes scikit-image bokeh matplotlib pycrypto
    - pip install psycopg2-binary
    - pip install git+https://github.com/paris-saclay-cds/ramp-workflow
    - pip install -e .
    # install ramp-engine
    - cd ramp-engine
    - pip install -e .
    - cd ..
script:
    - bash ci_tools/travis/test_ramp_board.sh
    - bash ci_tools/travis/test_ramp_engine.sh
after_success:
    - make code-analysis
notifications:
  email: true
