language: python
dist: trusty
env:
  global:
    - DATABOARD_USER=mrramp
    - DATABOARD_PASSWORD=mrramp
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7
services:
  - postgres
before_install:
    - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - conda env create python=$PYTHON_VERSION -f environment.yml
    - conda env create python=$PYTHON_VERSION -f environment_iris_kit.yml
    - source activate testenv
    - pip install .
    # install ramp-engine
    - cd ramp-engine
    - pip install .
    - cd ..
    # install ramp-database
    - cd ramp-database
    - pip install .
    - cd ..
script:
    - bash ci_tools/travis/test_ramp_board.sh
    - bash ci_tools/travis/test_ramp_engine.sh
    - bash ci_tools/travis/test_ramp_database.sh
after_success:
    - make code-analysis
notifications:
  email: true
