ramp:
    problem_name: iris
    event_name: iris_test
    event_title: "Iris event"
    event_is_public: true
    data_dir: /tmp/databoard_test/ramp-data/iris
    kit_dir: /tmp/databoard_test/ramp-kits/iris
    submissions_dir: /tmp/databoard_test/submissions
    predictions_dir: /tmp/databoard_test/preds
    logs_dir: /tmp/databoard_test/log
    sandbox_dir: starting_kit
worker:
    worker_type: conda
    conda_env: ramp-iris
dispatcher:
    hunger_policy: exit